stages:
  - build
  - deploy

variables:

build:
  stage: build
  image: docker:26.1.3
  services:
    - docker: 26.1.3-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u botman2000 -p zeriper2000
  script:
    - docker build -t botman2000/createx_back ./createx_back
    - docker build -t botman2000/createx_front ./createx_front
    - docker image push botman2000/createx_back
    - docker image push botman2000/createx_front